# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  watch-game-one:
    desc: run on file changes
    cmds:
      - pwd
      - watchexec --exit-on-error -e=odin --timings -r -c clear odin run ./game_one/main.odin -file -o:speed

  watch-multi-window:
    desc: run on file changes
    cmds:
      - pwd
      - watchexec --exit-on-error -e=odin --timings -r -c clear odin run ./multi_window -o:speed
